services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend/RAG_vectorDB:/app/RAG_vectorDB
      - ./backend/RAG_files:/app/RAG_files

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend